---
abstract: 'Convert POD data to various other formats'
author:
  - 'Russ Allbery <rra@stanford.edu>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: podlators
no_index:
  directory:
    - t
    - inc
requires:
  Encode: 0
  File::Spec: 0.8
  Pod::Simple: 3.06
version: v2.5.3
